### ISSUE TITLE
Mods won't load on Linux (CentOS)

### ISSUE THREAD

**Issue by GeurtsBob** [Nova-Atomic/Rimworld-Together#2]
Launching the server on CentOS works great, except when it comes to loading mods. It tries to access the about.xml file of each mod, but can't because the files are called About.xml and the system is case sensitive.

**Comment by Nova-Atomic** [comment]
Sorry for the issue! We just fixed it in latest release, if you were already running 1.0.6, please make sure to redownload.

**Comment by GeurtsBob** [comment]
No problem, thank you for the quick fix!
