### ISSUE TITLE
We need a detailed user manual document.

### ISSUE THREAD

**Issue by wycsdxq88** [Nova-Atomic/Rimworld-Together#24]
For example, how to use site to obtain resources. How can the resources obtained be extracted?

**Comment by Nova-Atomic** [comment]
For anything client related, we already have a wiki for that: https://rimworld-together.fandom.com/wiki/Rimworld_Together_Wiki
Server manual is being worked on and will be posted soon, will mark this issue as enhancement in the meantime.

**Comment by wycsdxq88** [comment]
Can you tell me how to obtain site resources?

**Comment by Nova-Atomic** [comment]
If you are the host of the server and aren't receiving any resources after the 30 minute mark, and there is a pawn inside if the site is personal, check your "SiteValues.json" file. It handles all of the site parameters and by default won't give any rewards unless configured

**Comment by wycsdxq88** [comment]
"PersonalFarmlandCost": "",
  "FactionFarmlandCost": "",
  "FarmlandRewardCount": "",
  "PersonalQuarryCost": "",
  "FactionQuarryCost": "",
  "Quarry Reward Count": "",
  "PersonalSawmillCost": "",
  "FactionSawmillCost": "",
  "SawmillRewardCount": "",
  "PersonalBankCost": "",
  "FactionBankCost": "",
  "BankRewardCount": "",
  "PersonalLaboratoryCost": "",
  "FactionLaboratoryCost": "",
  "LaboratoryRewardCount": "",
  "PersonalRefineryCost": "",
  "FactionRefineryCost": "",
  "RefineryRewardCount": "",
  "PersonalHerbalWorkshopCost": "",
  "FactionHerbalWorkshopCost": "",
  "HerbalWorkshopRewardCount": "",
  "PersonalTextileFactoryCost": "",
  "FactionTextileFactoryCost": "",
  "TextileFactoryRewardCount": "",
  "PersonalFoodProcessorCost": "",
  "FactionFoodProcessorCost": "",
  "FoodProcessorRewardCount": ""

How to set it up?

**Comment by wycsdxq88** [comment]
"PersonalQuarryCost": "1",

1X？？？

**Comment by wycsdxq88** [comment]
"PersonalQuarryCost": "1",

Is this correct?

**Comment by wycsdxq88** [comment]
Does that mean that every 30 minute interval, regardless of whether there are villains inside the site, resources will be automatically obtained?

**Comment by Nova-Atomic** [comment]
No, as the wiki says, a personal site needs pawns inside to get rewards. Only if there are pawns inside or the site is a faction site rewards will arrive pasively

**Comment by wycsdxq88** [comment]
Where can I see the reward that arrives? Or how can I obtain these rewards?
