### ISSUE TITLE
How to use game's mods files 

### ISSUE THREAD

**Issue by Cubbird46** [Nova-Atomic/Rimworld-Together#3]
Hi ! 

In the Description you say where to put mod files but, how do you get them ?? 

From the Steam Workshop directory, the files are all messed up with numbers (example : 294100, 563718, etc)
So how do you know what mod is this file or that one ?

Also, does the order of activation IG have to be the same in the MODS folder of the server ?

(I'm very sorry if this is hard to understand, it's my first Issue on Github... I don't know how this works) :( 

Thanks in advance for your time and responses !

**Comment by Nova-Atomic** [comment]
Hello! Welcome to GitHub!

First off, the mod order of the server doesn't matter at all, you can sort them using whatever method you wish!

Secondly, setting up the modlist can be a bit of a pain if doing so with a high quantity of mods, so there are two main ways of doing it:

A - Get the mods directly from the workshop folder (the folder name, which is composed by numbers, is the id of the mod and can be checked from the url whenever you visit a workshop item)

B - I made a tool in the past that helps with it, translating the numbers into the actual mod name. You can get it from here: https://github.com/Nova-Atomic/Library

If you decide to go with B, make sure to use it on a separate copy of the mods (Just copy & paste them somewhere and use the app on the copies) as Rimworld doesn't like having the original folder's name changed.

**Comment by Cubbird46** [comment]
Thank you very much !! You saved me ! xD

I did it with the A even if it took time ^^'

Thanks again !
