### ISSUE TITLE
Trade request not including raw materials

### ISSUE THREAD

**Issue by megastruktur** [Nova-Atomic/Rimworld-Together#31]
While trying to request raw materials (like wood, steel, etc.) I came to my friends base and started the trade.
However no raw materials are there in my friends "select" list. There are only: only animals, pawns and dismounted structures.

**Comment by megastruktur** [comment]
Upd: Trading won't count (presumably) materials which alre located on these shelves
![B3EJPf2](https://github.com/Nova-Atomic/Rimworld-Together/assets/2911416/5b84888a-f299-4618-b6e7-b94a3302582b)

**Comment by emelrad12** [comment]
fixed with 9c6797ab001d71f69e3d1160df1fd2c0516d04fd
