### ISSUE TITLE
Illegal Action

### ISSUE THREAD

**Issue by Oceanwaterperson** [Nova-Atomic/Rimworld-Together#38]
Hey, so since me and my mates had to restart, due to a weird map error, i had to delete all the folders and savegame to restart a full fresh restart.
We're all playing via vpn Tunneling but after the restart one of my mates can't connect to the game anymore- once he finished creating his colony and starts pressing start- the server log spits out an "illegal action error"- but the log doesn't specify any more info. What could be the reason behind that? 
Since the first game we didn't change a single mod setting nor added or removed a mod. 
Thanks:) and love the mod so far!

**Comment by Nova-Atomic** [comment]
Hello there, could you send both you and your friend's game logs through here whenever you experience the issue again, so we can take a look at them?
