### ISSUE TITLE
I copied my mod folder and it is adding _copy to the name of all my mods

### ISSUE THREAD

**Issue by RyanMurgar** [Nova-Atomic/Rimworld-Together#42]
Hello,

I created a VPN server and the setup looks good. I can connect to the server, however when I try to connect I get an issue with a discrepency between my required mods and my disqualified mods. 

They are identical mods except they have _copy at the end of the file on the server side. I cannot find when to change the names on the server. How should I approach this. Also I am not very good at programming/have zero experience with it.

**Comment by Nova-Atomic** [comment]
Could you double check the mods that have the "_copy" termination are from the server and not from the client? There have been cases of this happening in client mods so being the other way around seems weird.

Could you also attach the mod list you are using and tell us if you are using rimpy to create the modlist by any chance? If so, are you trying to load mods that are both "Steam" and "Local" versions? (IE: you have a copy of a mod both in the local mods folder and in the workshop folder)

**Comment by RyanMurgar** [comment]
![image](https://github.com/Nova-Atomic/Rimworld-Together/assets/144645334/906c408c-73e9-4115-9788-0f9a46024a6d)
I tried loading the server today to check on the error and this is my current message.

**Comment by Nova-Atomic** [comment]
Check on the Github section "Enabling Core & DLCs" on how to install the core of the game into the server
