### ISSUE TITLE
Save path incorrect on OSX with Steam Rimworld

### ISSUE THREAD

**Issue by frogcm** [Nova-Atomic/Rimworld-Together#47]
**Symptom:** Game would get through world and settlement setup but freeze on a black screen with potentially some skewed text when zooming to the settlement. Seen on OSX 13.4.1 using Steam to launch Rimworld. Reproduced on a second OSX machine. No issue under Windows 10 connecting to the same server.

On OSX, Player.log had this entry:
`Exception from asynchronous event: System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/<redacted>/Library/Application Support/ludeon.rimworld/Saves/Server - 192.168.22.17 - initial.rws".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00164] in <eae584ce26bc40229c1b1aa476bfa589>:0 
`

A search for the file reveled it at a different path:
`/Users/<redacted>/Library/Application Support/RimWorld/Saves/Server - 192.168.22.17 - initial.rws`

The folder `~/Library/Application Support/ludeon.rimworld/` contained only a subfolder for `Rimworld Together` containing configuration JSON files.

Moving `~/Library/Application Support/ludeon.rimworld/Rimworld Together` to `~/Library/Application Support/RimWorld/` and symlinking `~/Library/Application Support/ludeon.rimworld` to `~/Library/Application Support/RimWorld` resolved the issue and allowed the game and mod to run as expected.

Issue seems to be an different root path returned by `Application.persistentDataPath` than what is used by the base game for saves here: https://github.com/Nova-Atomic/Rimworld-Together/blob/fe47e10242f84f4b1eaec0dfba08fcc7dcb9b9fa/Source/Client/Core/Main.cs#L51

Based on quick survey of other mods, it looks like it should be using "GenFilePaths" object to find paths. For instance, the save folder path should be returned by something like `GenFilePaths.SavedGamesFolderPath`.

**Comment by frogcm** [comment]
I made a fork and commit that _should_ fix the issue, but I do not have the resources to compile and test it and so I am hesitant to start a pull request: https://github.com/frogcm/Rimworld-Together/commit/8902356f619676e62d20f24fa32c51e4e5b0b5e8

**Comment by Nova-Atomic** [comment]
> I made a fork and commit that _should_ fix the issue, but I do not have the resources to compile and test it and so I am hesitant to start a pull request: [frogcm@8902356](https://github.com/frogcm/Rimworld-Together/commit/8902356f619676e62d20f24fa32c51e4e5b0b5e8)

Just double checked the code to make sure it was all working and it all seems good. Make sure to request the changes if you want the contribution.
