### ISSUE TITLE
Login is impossible after updating to 1.1.0

### ISSUE THREAD

**Issue by RevoluPowered** [Nova-Atomic/Rimworld-Together#52]
Updating to 1.1.0 added compression but adds errors into the loading of existing save files 

The log is as follows:

![image](https://github.com/Nova-Atomic/Rimworld-Together/assets/748770/e5ff6354-9b21-4b9e-adaa-45f807d0c7a7)

The saves are here:
- all user passwords changed to "guest"
I recommend testing guest account to produce this bug

I tried already to swap the user details out from a new account but no luck.

Drive for the save files
https://drive.google.com/file/d/12th64p7YraOijF0tmg9rqC6g4BdcvOOk/view?usp=sharing

**Comment by Nova-Atomic** [comment]
Hello, did you use the save converter to patch old saves to 1.1.0?

**Comment by RevoluPowered** [comment]
> Hello, did you use the save converter to patch old saves to 1.1.0?

So, I wasn't sure what version we were running for the old version, I believe it was 1.0.9, dumb question where can I check the version number as the executable is set to 1.0.0 for all binaries

**Comment by RevoluPowered** [comment]
Ah I see never mind I will run that converter

**Comment by RevoluPowered** [comment]
Ran the converter but no joy

![image](https://github.com/Nova-Atomic/Rimworld-Together/assets/748770/f7fb86e6-5b25-4f74-a15c-e9d449b04066)

**Comment by RevoluPowered** [comment]
![20231113232958_1](https://github.com/Nova-Atomic/Rimworld-Together/assets/748770/8a701569-0e14-4bfa-801f-df9c9b509ff5)

**Comment by Nova-Atomic** [comment]
Any chance you could upload your game logs into here? Whole server logs would be useful too

**Comment by RevoluPowered** [comment]
> Any chance you could upload your game logs into here? Whole server logs would be useful too. Also, just to confirm any possible scenario, was this your use of the tool?
> 
> * Drag the local save (.rws) file into the converter.
> * Provide the username for the save.
> * Drag the resulting file (.mpsave) into the server folder.

Ah, no what I did was assume the mpsave was the correct save to convert, my bad I can try that tomorrow, will update you if this works

**Comment by RevoluPowered** [comment]
We checked and managed to upgrade our saves by grabbing them from our save folder and using the save-upgrader, thank you for your help!
