### ISSUE TITLE
[Disallowed] >  ludeon.rimworld

### ISSUE THREAD

**Issue by Aether42** [Nova-Atomic/Rimworld-Together#54]
If I mark any mods as required, it dissalows the core, ludeon.rimworld.
How do I make "ludeon.rimworld" a required mod, there's no mod folder for it (that I know of).

I tired making a dummy "Core" folder in Required mods, but then it needed an xml and that's getting beyond my abilities.

![image](https://github.com/Nova-Atomic/Rimworld-Together/assets/11468445/f8475b80-d6c8-474c-85b0-d225b5af1f25)

**Comment by Aether42** [comment]
I am able to resolve Harmony and Rimworld together by adding those as required mods, but can't figure out how to do that for core game.

**Comment by Zetal911** [comment]
This is not an issue. Read the readme. https://github.com/Nova-Atomic/Rimworld-Together#enabling-core--dlcs
