### ISSUE TITLE
Reforming caravan after online visit doesn't leave colony

### ISSUE THREAD

**Issue by imagitama** [Nova-Atomic/Rimworld-Together#57]
Form caravan to visit another online player, visit their colony (online), re-form caravan but for both players the game thinks you are still visiting and won't let you do anything else and will prevent both players from changing game speed.

I can't visit the same colony again as it thinks I am already visiting them

Active mods:

<img width="250" alt="enabled mods" src="https://github.com/Nova-Atomic/Rimworld-Together/assets/1967342/8605797f-6ac8-4b89-a575-0701446c6c97">

What I see when I visit someone else's colony:

![image](https://github.com/Nova-Atomic/Rimworld-Together/assets/1967342/9ea1aaf8-6483-49e1-ba28-c147df9e52a2)

**Comment by Nova-Atomic** [comment]
Hello, when exiting the visiting map, did you use the specified command (/sv) to do so? Online visiting is in need of some work and the only way to leave for now is to use it.

If nothing broke in the process, you should have received a similar message than this while trying to visit someone.

![Capture](https://github.com/Nova-Atomic/Rimworld-Together/assets/96362005/a01fffa3-92e7-4207-9bec-eaa6ee54dc6d)

**Comment by imagitama** [comment]
> Hello, when exiting the visiting map, did you use the specified command (/sv) to do so?

Nope. I remember seeing that message but completely forgot about it.
