### ISSUE TITLE
Switch from reading mod xml files to read mods id

### ISSUE THREAD

**Issue by MADxingjin** [Nova-Atomic/Rimworld-Together#9]
Extract & copying tons of about.xml takes time and consumes ones sanity, Leading to HIGH BREAK RISK.
Instead We can uses three lists of mod package ids to do the job, and ships a predefined list filled with requirements for the mod alongside the server executable.
Also provide commands to make new mods required/optional/forbidden by giving mod package ids at runtime without restart.

**Comment by Nova-Atomic** [comment]
Hello there, one of our devs @MisteriousGoose is working on a system in which mods and their settings will be able to be sent directly from the server into each player. For this system server admins will need to directly upload the whole contents of the mods into the server, making this proposed enhancement non-aplicable.
